"""
Django settings for encuaestas_conjuntos project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)!_k7!g6_fk*0_5zo9!1eblm(l(o&)88nbh39!c(3!v#*$k90r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'estudiantes',  # Agrega la aplicación 'estudiantes' aquí
    'corsheaders',  # Agrega esta línea
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'encuaestas_conjuntos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'encuaestas_conjuntos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# # CREDENCIALES PARA DB LOCAL
# ENCUESTAS_DB_HOST = 'viaduct.proxy.rlwy.net'  # Aquí debes poner la dirección real del host de tu base de datos
# ENCUESTAS_DB_NAME = 'railway'
# ENCUESTAS_DB_PASSWORD = 'ywRqaEthyBunUUQcjsdbzcFRVgmzBMKz'
# ENCUESTAS_DB_PORT = '13480'  # El puerto debe ser un string
# ENCUESTAS_DB_USER = 'postgres'


# # Resto de la configuración de Django...

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': ENCUESTAS_DB_NAME,
#         'USER': ENCUESTAS_DB_USER,
#         'PASSWORD': ENCUESTAS_DB_PASSWORD,
#         'HOST': ENCUESTAS_DB_HOST,
#         'PORT': ENCUESTAS_DB_PORT,
#     }
# }


load_dotenv()


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('ENCUESTAS_DB_NAME'),
        'USER': os.getenv('ENCUESTAS_DB_USER'),
        'PASSWORD': os.getenv('ENCUESTAS_DB_PASSWORD'),
        'HOST': os.getenv('ENCUESTAS_DB_HOST'),
        'PORT': os.getenv('ENCUESTAS_DB_PORT'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGIN = ['*']
