# Generated by Django 5.0.3 on 2024-03-27 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T003DatosConjunto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=255, unique=True)),
                ('T003nombre', models.CharField(max_length=255)),
                ('T003direccion', models.CharField(max_length=255)),
                ('T003numero_administracion', models.CharField(max_length=255)),
                ('T003tel', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'T003DatosConjunto',
            },
        ),
        migrations.CreateModel(
            name='T004Personas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('T004cell', models.CharField(max_length=255)),
                ('T004nombre', models.CharField(max_length=255)),
                ('T004cc', models.CharField(max_length=255)),
                ('T004correo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'T004Personas',
            },
        ),
        migrations.CreateModel(
            name='T005TipoAsistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('T005tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'T005TipoAsistencia',
            },
        ),
        migrations.CreateModel(
            name='T006TipoEncuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('T006tipo_encuesta', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'T006TipoEncuesta',
            },
        ),
        migrations.CreateModel(
            name='T007TiposDeCasa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('T007NombreTipoo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'T007TiposDeCasa',
            },
        ),
        migrations.CreateModel(
            name='T002DatosCasa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('T002nombre_casa', models.CharField(max_length=255)),
                ('T002propietario', models.CharField(max_length=255)),
                ('T002ponderacion', models.IntegerField()),
                ('id_conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.t003datosconjunto')),
                ('id_tipo_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.t007tiposdecasa')),
            ],
            options={
                'db_table': 'T002DatosCasa',
            },
        ),
        migrations.CreateModel(
            name='T001Encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('T001nombre_encuesta', models.CharField(max_length=255)),
                ('T001numero_control', models.CharField(max_length=255)),
                ('id_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.t002datoscasa')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.t004personas')),
                ('id_tipo_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.t005tipoasistencia')),
                ('id_tipo_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.t006tipoencuesta')),
            ],
            options={
                'db_table': 'T001Encuesta',
            },
        ),
    ]
