# Generated by Django 5.0.3 on 2024-03-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t004personas',
            name='T004activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t004personas',
            name='T004coeficiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t004personas',
            name='T004direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t004personas',
            name='T004genero',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
